### PR TITLE
Feature/feature medication crud

### PR DESCRIPTION
**Pull request by xavier-campos-diaz**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/services/MedicationAdapter.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrObtainAllPetMedication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteMedication.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPetMedication.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrUpdateMedication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrUpdateMedication.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteMedication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetMedicationFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrObtainAllPetMedications.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Medication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPetMedication.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/services/StubMedicationService.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5400786&bid=17705370)

**Review by enrichp — APPROVED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrUpdateMedication.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteMedication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetMedicationFragment.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrUpdateMedication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Medication.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrObtainAllPetMedication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPetMedication.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrObtainAllPetMedications.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/services/StubMedicationService.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPetMedication.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/services/MedicationAdapter.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteMedication.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5400786&bid=17705370)

**Review by AlbertPG — APPROVED** [review]
Okey

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteMedication.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrUpdateMedication.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPetMedication.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetMedicationFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/services/StubMedicationService.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Medication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrNewPetMedication.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteMedication.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/services/MedicationAdapter.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrObtainAllPetMedications.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrUpdateMedication.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrObtainAllPetMedication.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5400786&bid=17705370)

**Pull request merged**
