### PR TITLE
Feature/feature change username

### PR DESCRIPTION
**Pull request by enrichp**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrExistsUsername.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrChangeUsername.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrExistsUsername.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrChangeUsername.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5361539&bid=17568066)

**Review by xavier-campos-diaz — APPROVED** [review]

**Review by AlbertPG — APPROVED** [review]
Okey, I approve it

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrChangeUsername.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrChangeUsername.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrExistsUsername.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrExistsUsername.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5361539&bid=17568066)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrChangeUsername.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrExistsUsername.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrChangeUsername.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrExistsUsername.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5361539&bid=17568066)

**Pull request merged**
