### PR TITLE
Feature/feature start walking

### PR DESCRIPTION
**Pull request by AlbertPG**

### CODE REVIEW

**Review by danicm47 — DISMISSED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Medication.java  -4
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/medication/TrNewPetMedication.java  -12
         

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/walks/WalkFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/services/MessagingService.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Walk.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllWalks.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllWalks.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrAddWalk.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/WalkPets.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/utilities/LocationUpdater.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrAddWalk.java  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5516822&bid=18076912)

**Review by danicm47 — DISMISSED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Medication.java  -4
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/medication/TrNewPetMedication.java  -12
         

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllWalks.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Walk.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/walks/WalkFragment.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrAddWalk.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrAddWalk.java  8
- app/src/main/java/org/pesmypetcare/mypetcare/utilities/LocationUpdater.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/services/MessagingService.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/WalkPets.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllWalks.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5516822&bid=18076912)

**Review by danicm47 — DISMISSED** [review]

**Review by enrichp — DISMISSED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/walks/WalkFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrAddWalk.java  8
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllWalks.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrAddWalk.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/WalkPets.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllWalks.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/services/MessagingService.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Walk.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/utilities/LocationUpdater.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5516822&bid=18076912)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllWalks.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/services/MessagingService.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllExercises.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/WalkPets.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrAddWalk.java  8
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllWalks.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllExercises.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/utilities/LocationUpdater.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrAddWalk.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/walks/WalkFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Walk.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5516822&bid=18076912)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllExercises.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllWalks.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/walks/WalkFragment.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrAddWalk.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllExercises.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrAddWalk.java  8
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/WalkPets.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Walk.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/utilities/LocationUpdater.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/services/MessagingService.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllWalks.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5516822&bid=18076912)

**Review by enrichp — DISMISSED** [review]

**Review by danicm47 — DISMISSED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/WalkPets.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/services/MessagingService.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllExercises.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/utilities/LocationUpdater.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrAddWalk.java  8
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrAddWalk.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Walk.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllWalks.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllWalks.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllExercises.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/walks/WalkFragment.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5516822&bid=18076912)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/utilities/LocationUpdater.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/services/MessagingService.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrAddWalk.java  8
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllWalks.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrAddWalk.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Walk.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/WalkPets.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/walks/WalkFragment.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllExercises.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/infopet/TestTrGetAllWalks.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/exercise/TrGetAllExercises.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5516822&bid=18076912)

**Review by enrichp — APPROVED** [review]

**Review by danicm47 — APPROVED** [review]

**Pull request merged**
