### PR TITLE
Feature/feature pet health

### PR DESCRIPTION
**Pull request by AlbertPG**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PetHealthInfo.java  14
         

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWashFrequency.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/healthbottomsheet/HealthBottomSheet.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StatisticData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWeight.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StubStatisticData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWeight.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/BarChart.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/StatisticButton.java  2
         

Clones added
============
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5358836&bid=17558969)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StatisticData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/StatisticButton.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StubStatisticData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWeight.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWeight.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/healthbottomsheet/HealthBottomSheet.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWeight.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWashFrequency.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/BarChart.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
         

Clones added
============
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5358836&bid=17558969)

**Review by enrichp — APPROVED** [review]

**Review by xavier-campos-diaz — APPROVED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWashFrequency.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/healthbottomsheet/HealthBottomSheet.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWeight.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/BarChart.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StubStatisticData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/StatisticButton.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StatisticData.java  2
         

Clones added
============
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5358836&bid=17558969)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/BarChart.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/StatisticButton.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWashFrequency.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StubStatisticData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/healthbottomsheet/HealthBottomSheet.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWashFrequency.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWeight.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWeight.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StatisticData.java  2
         

Clones added
============
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5358836&bid=17558969)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/StatisticButton.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/BarChart.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWashFrequency.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/healthbottomsheet/HealthBottomSheet.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWeight.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StubStatisticData.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StatisticData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  2
         

Clones added
============
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5358836&bid=17558969)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StubStatisticData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWashFrequency.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/StatisticButton.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/healthbottomsheet/HealthBottomSheet.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWashFrequency.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/BarChart.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWeight.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StatisticData.java  2
         

Clones added
============
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5358836&bid=17558969)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ app/src/main/java/org/pesmypetcare/mypetcare/features/pets/PetHealthInfo.java  14
         

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StubStatisticData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWashFrequency.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWeight.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWashFrequency.java  3
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrAddNewWashFrequency.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrDeleteWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/StatisticData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/StatisticButton.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/BarChart.java  4
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/TrAddNewWeight.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/healthbottomsheet/HealthBottomSheet.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
         

Clones added
============
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/DailyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeightData.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyExerciseData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WashFrequencyData.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWeight.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/ExerciseFrequencyData.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWashFrequency.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5358836&bid=17558969)

**Pull request merged**
