### PR TITLE
Feature/feature tabs for pet info

### PR DESCRIPTION
**Pull request by AlbertPG**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetBasicFragment.java  3
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetHealthFragment.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetMealsFragment.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetFragmentAdapter.java  5
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetMedicationFragment.java  1
- app/src/androidTest/java/org/pesmypetcare/mypetcare/activities/fragments/TestInfoPetBasicFragment.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5315416&bid=17395707)

**Review by enrichp — APPROVED** [review]

**Review by xavier-campos-diaz — APPROVED** [review]

**Comment by marclll** [comment]
No pasa todos los test

**Review by marclll — CHANGES_REQUESTED** [review]
No pasa todos los test

**Review by marclll — APPROVED** [review]
La ultima

**Pull request merged**
