### PR TITLE
Hotfix/v2.0.1 (master)

### PR DESCRIPTION
**Pull request by AlbertPG**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/pethealth/TrGetAllWeights.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/pethealth/TestTrGetAllWeights.java  1
         

Complexity decreasing per file
==============================
+ app/src/main/java/org/pesmypetcare/mypetcare/controllers/user/TrDeleteUser.java  -1
         

Clones removed
==============
+ app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5581370&bid=18295421)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/pethealth/TrGetAllWeights.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/pethealth/TestTrGetAllWeights.java  1
         

Complexity decreasing per file
==============================
+ app/src/main/java/org/pesmypetcare/mypetcare/controllers/user/TrDeleteUser.java  -1
         

Clones removed
==============
+ app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5581370&bid=18295421)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/pethealth/TrGetAllWeights.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/pethealth/TestTrGetAllWeights.java  1
         

Complexity decreasing per file
==============================
+ app/src/main/java/org/pesmypetcare/mypetcare/controllers/user/TrDeleteUser.java  -1
         

Clones removed
==============
+ app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5581370&bid=18295421)

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/pethealth/TrGetAllWeights.java  4
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/pethealth/TestTrGetAllWeights.java  1
         

Complexity decreasing per file
==============================
+ app/src/main/java/org/pesmypetcare/mypetcare/controllers/user/TrDeleteUser.java  -1
         

Clones removed
==============
+ app/src/main/java/org/pesmypetcare/mypetcare/activities/views/chart/statisticdata/WeeklyKilocaloriesData.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5581370&bid=18295421)

**Review by enrichp — APPROVED** [review]

**Review by danicm47 — APPROVED** [review]

**Review by santidrj — APPROVED** [review]
:+1:

**Pull request merged**
