### PR TITLE
feature_Washing history

### PR DESCRIPTION
**Pull request by enrichp**

### CODE REVIEW

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWash.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrDeleteWash.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrUpdatePetWash.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPetWash.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/WashesControllersFactory.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Wash.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrObtainAllPetWashes.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrObtainAllPetWashes.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrUpdateWash.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetWashing.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5492203&bid=17998809)

**Review by xavier-campos-diaz — DISMISSED** [review]

**Review by AlbertPG — DISMISSED** [review]
Okey

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/WashesControllersFactory.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrUpdateWash.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrDeleteWash.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrObtainAllPetWashes.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetWashing.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPetWash.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrUpdatePetWash.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Wash.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrObtainAllPetWashes.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWash.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5492203&bid=17998809)

**Review by xavier-campos-diaz — DISMISSED** [review]

**Comment by santidrj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrNewPetWash.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/activities/fragments/infopet/InfoPetWashing.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrObtainAllPetWashes.java  2
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrUpdateWash.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrUpdatePetWash.java  2
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrObtainAllPetWashes.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/WashesControllersFactory.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/features/pets/Wash.java  1
- app/src/main/java/org/pesmypetcare/mypetcare/controllers/washes/TrDeleteWash.java  1
- app/src/test/java/org/pesmypetcare/mypetcare/controllers/TestTrDeleteWash.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/Grupo13-PES-Mascotas/PES_My-Pet-Care/pullRequest?prid=5492203&bid=17998809)

**Review by xavier-campos-diaz — APPROVED** [review]

**Review by AlbertPG — APPROVED** [review]
Okey

**Pull request merged**
